# Generated by Django 5.0.5 on 2024-06-22 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_promocode_alter_order_cvc_alter_order_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
